# Generated by Django 2.0.7 on 2018-11-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled',
            field=models.IntegerField(default=2018),
        ),
    ]
